### ISSUE TITLE
CarPlay POI Glitch

### ISSUE THREAD

**Issue by zaaaacch** [ClutchEngineering/ElectricSidecar#29]
The POI markers on the CarPlay map are messed up for some reason:
![image](https://github.com/user-attachments/assets/bc2f77c0-fb0a-4126-af11-3a2881db4399)

**Comment by jverkoey** [comment]
This is a bug with Apple's MapKit; tracking with FB13820990 and sharing screenshots each time it happens. I'll keep this issue open until this is resolved.

**Comment by jverkoey** [comment]
The not-ideal workaround is a restart of the app, but it also sometimes resolves itself on its own after 5-10 minutes.

**Comment by jverkoey** [comment]
Should be fixed in v1.18!
